### ISSUE TITLE
Image loading is slow

### ISSUE THREAD

**Issue by mathewt-p** [Band-of-Techies/my_plant_store_admin_BE_FE#19]
Make use of cloudinary services
https://cloudinary.com/documentation/node_image_manipulation

**Comment by GokulkrishnanRvm** [comment]
transformation: [
        { width: 500, height: 500, crop: "limit" },
        { quality: "auto:best" },
        { fetch_format: "auto" },
        { aspect_ratio: "3:4", crop: "fill" }
    ] added the above code to the existing cloudinary index.js file for better image output.
